name: car_rental
description: A new Flutter project.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.1.5 <4.0.0'

dependencies:
  cupertino_icons: ^1.0.2
  flutter:
    sdk: flutter
  flutter_screenutil: ^5.9.3

dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  # Register asset directories (add/remove as your project needs).
  assets:
    - assets/images/
    - assets/icons/
    - assets/svg/
    - assets/lottie/
    - assets/json/

  # Tajawal font family (weights mapped correctly)
  fonts:
    - family: Tajawal
      fonts:
        - asset: assets/fonts/Tajawal-ExtraLight.ttf
          weight: 200
        - asset: assets/fonts/Tajawal-Regular.ttf
          weight: 400
        - asset: assets/fonts/Tajawal-Medium.ttf
          weight: 500
        - asset: assets/fonts/Tajawal-Bold.ttf
          weight: 700
        - asset: assets/fonts/Tajawal-ExtraBold.ttf
          weight: 800
        - asset: assets/fonts/Tajawal-Black.ttf
          weight: 900

# VS Code “Flutter Assets” extension config (TOP-LEVEL, not under `flutter`)
flutter_assets:
  assets_path: assets/images/
  output_path: lib/core/utils
  filename: assets.dart
  # field_prefix: ''     # optional; uncomment to customize field names
