name: car_rental
description: A new Flutter project.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.1.5 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # State Management
  flutter_bloc: ^9.1.1

  # UI & Responsiveness
  flutter_screenutil: ^5.9.3
  cupertino_icons: ^1.0.2
  flutter_svg: ^2.0.10+1

  # Networking
  dio: ^5.9.0
  retrofit: ^4.5.0
  pretty_dio_logger: ^1.4.0

  # Dependency Injection
  get_it: ^8.2.0

  # UI Widgets & Input
  phone_text_field: ^2.0.0
  pinput: ^5.0.2

  # Annotations for codegen (must align with freezed 2.4.x)
  freezed_annotation: ^2.4.4
  json_annotation: ^4.9.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

  # Code generation (Dart 3.1.5 compatible)
  build_runner: ^2.4.9
  json_serializable: ^6.8.0
  retrofit_generator: ^8.2.1
  freezed: ^2.4.7


flutter:
  uses-material-design: true

  assets:
    - assets/images/

  fonts:
    - family: Tajawal
      fonts:
        - asset: assets/fonts/Tajawal-ExtraLight.ttf
          weight: 200
        - asset: assets/fonts/Tajawal-Regular.ttf
          weight: 400
        - asset: assets/fonts/Tajawal-Medium.ttf
          weight: 500
        - asset: assets/fonts/Tajawal-Bold.ttf
          weight: 700
        - asset: assets/fonts/Tajawal-ExtraBold.ttf
          weight: 800
        - asset: assets/fonts/Tajawal-Black.ttf
          weight: 900

# VS Code “Flutter Assets” extension config
flutter_assets:
  assets_path: assets/images/
  output_path: lib/core/utils
  filename: assets.dart
